# Generated by Django 4.2.4 on 2023-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
