# Generated by Django 4.2.4 on 2023-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
