# Generated by Django 4.2.4 on 2023-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_bestseller",
            field=models.BooleanField(default=False),
        ),
    ]
